#ifndef SPRITE_TEST_PATTERN_H
#define SPRITE_TEST_PATTERN_H

#define HP_T 0x00
#define HP_G 0x55
#define HP_B 0xaa
#define HP_W 0xff

#define TEST_COL_TRANSPARENT \
	HP_T, HP_T, HP_T, HP_T, HP_T, HP_T, HP_T, HP_T, \
	HP_T, HP_T, HP_T, HP_T, HP_T, HP_T, HP_T, HP_T

#define TEST_COL_BLACK \
	HP_B, HP_B, HP_B, HP_B, HP_B, HP_B, HP_B, HP_B, \
	HP_B, HP_B, HP_B, HP_B, HP_B, HP_B, HP_B, HP_B

#define TEST_COL_GREY \
	HP_G, HP_G, HP_G, HP_G, HP_G, HP_G, HP_G, HP_G, \
	HP_G, HP_G, HP_G, HP_G, HP_G, HP_G, HP_G, HP_G

#define TEST_COL_WHITE \
	HP_W, HP_W, HP_W, HP_W, HP_W, HP_W, HP_W, HP_W, \
	HP_W, HP_W, HP_W, HP_W, HP_W, HP_W, HP_W, HP_W

static const u8 testPatternSprite[SPRITE_BYTES] =
{
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE,
	TEST_COL_TRANSPARENT, TEST_COL_BLACK, TEST_COL_GREY, TEST_COL_WHITE
};

#endif
